### ISSUE TITLE
Port to Lua jit jvm disabled 

### ISSUE THREAD

**Issue by ghost** [KCreate/stackvm#9]
Hello,

First of all, I follow you and wish you very much success for your projects. I really enjoy your ideas behind the projects. 

My subject of this issue is, if I am allowed to port this vm to Lua jit with the jvm disabled. I’d like to use lua to address the above challenge cause it’s freaking fast and I think it will work. If I’m allowed, I’ll add you to the license file.

Again, I love your work and I am really engaged for cooperating at jobs in compiler/vm/interpreter funds. 

Thanks and regards

Timo S.

**Comment by KCreate** [comment]
Hey

Thanks for the kind words!
Absolutely you can port this to Lua, this project is open-source, so do as you please.

**Comment by ghost** [comment]
Great thanks 

But I’ve to think if I’ll not probably implement it with C using node addons for more flexibility. However I’ll take a look on this.😂
